group 'com.huazi.gtads_vivo'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
        maven { url 'http://maven.vivo.xyz/nexus/content/repositories/releases/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'http://maven.vivo.xyz/nexus/content/repositories/releases/' }
        flatDir {
            dirs "${project.rootDir}/libs"
        }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.huazi.gtads_vivo'
    }

    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }

    defaultConfig {
        minSdkVersion 20
    }

    dependencies {
        testImplementation 'org.jetbrains.kotlin:kotlin-test'
        testImplementation 'org.mockito:mockito-core:5.1.1'
        implementation "com.android.support:support-annotations:28.0.0"
        implementation "com.android.support:support-v4:28.0.0"
        implementation "com.android.support:recyclerview-v7:28.0.0"
        implementation "com.android.support:appcompat-v7:28.0.0"
        compileOnly(name: 'open_ad_6.2.5.0_024d3e98a_3488g', ext: 'aar')
        compileOnly(name: 'oaid_sdk_1.0.25', ext: 'aar')
        compileOnly(name: 'GDTSDK.unionNoPlugin.4.580.1450', ext: 'aar')
        compileOnly(name: 'open_ad_sdk_6.4.6.6', ext: 'aar')
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}
rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'http://maven.vivo.xyz/nexus/content/repositories/releases/' }
        flatDir {
            dirs project(':gtads_vivo').file('libs')
        }
    }
}